### ISSUE TITLE
Invalid or corrupt jarfile airsonic.war on latest

### ISSUE THREAD

**Issue by xeals** [linuxserver/docker-airsonic#17]
I've just updated to the `latest` image and trying to run the container just gives nothing but

```
Error: Invalid or corrupt jarfile airsonic.war
```

repeated in the logs.

Everything was working fine on the previous build (87, ID `0026a55e0322`).

---

`docker-compose` entry:

```yaml                                                                                                         
airsonic:
  container_name: airsonic
  image: linuxserver/airsonic
  restart: unless-stopped
  networks:
    - internal
  volumes:
    - ./music:/music
    - ./playlists:/playlists
    - ./airsonic/config:/config
    - ./airsonic/media:/media
    - ./podcasts:/podcasts
  environment:
    PUID: 1000
    PGID: 1000
```

**OS**: Ubuntu 18.04
**Docker**: 17.12.1-ce
**Docker-compose**: 1.17.1
