### ISSUE TITLE
Cannot connect on 4040

### ISSUE THREAD

**Issue by karl0ss** [linuxserver/docker-airsonic#18]
Is this working yet? I have pulled the latest version of the container, and can see via the logs it is scanning my music dir, but I am unable to access on 4040

Even if i console into the container and "curl http://localhost:4040" I am not getting anything from the curl command.

Am i doing something wrong?

**Comment by j0nnymoe** [comment]
Post your docker run/however you've deployed the container.

**Comment by karl0ss** [comment]
```
services:
  airsonic:
    image: linuxserver/airsonic
    container_name: airsonic
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    ports:
      - "4040:4040"    
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/airsonic:/config
      - /docker/music:/music
      - /docker/music/playlists:/playlists
      - /docker/music/podcasts:/podcasts

```
